name: Python Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Safety
      run: |
        python -m pip install --upgrade pip
        pip install safety

    - name: Run Safety Scan
      run: |
        echo "Running safety scan for dependencies..."
        python -m pip freeze > requirements.txt
        safety scan --file=requirements.txt --output=json > safety-report.json

    - name: Display Safety Report
      run: cat safety-report.json
