name: Python Code Standards and Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Tools
      run: |
        python -m pip install --upgrade pip
        pip install ruff safety

    - name: Run Ruff for Coding Standards
      run: ruff check src

    - name: Run Safety for Dependency Vulnerabilities
      run: |
        echo "Checking for vulnerabilities using Safety"
        if [ -f requirements.txt ]; then
          echo "requirements.txt found. Scanning dependencies..."
          safety scan --file=requirements.txt --output=json > safety-report.json || exit 1
        else
          echo "requirements.txt not found. Scanning environment..."
          python -m pip freeze > env-requirements.txt
          safety scan --file=env-requirements.txt --output=json > safety-report.json || exit 1
        fi

    - name: Display Safety Report
      run: cat safety-report.json
